"""Instance generator for the quantum_espresso silicon band-structure MCP E2E fake task.

A seeded RNG picks a plane-wave cutoff, a k-point spacing and a number of
band-path points. Through the qe-mcp server (Quantum ESPRESSO 7.5) the agent
must drive a five-tool chain on silicon:

    qe_list_pseudopotentials -> qe_suggest_kpoints -> qe_workflow_bandstructure
                             -> qe_list_files -> qe_read_bands

where every step feeds the next: the suggested grid is the band-structure
run's SCF grid, the run's directory is what gets listed, and the band file
the listing returns is what gets read. The answer is the run's energies and
band edges plus what the band file and the pseudopotential index say.

Where the reference comes from
------------------------------
DFT cannot be recomputed here: ``pw.x`` and ``bands.x`` exist only inside the
server's pinned conda environment, and a task runtime may not build one. The
DFT numbers are therefore **measured** against that environment by
``scripts/mcp/e2e/measure_qe_table.py`` and carried in ``MEASURED`` below,
keyed by ``(ecutwfc, grid, npoints_band)`` — the three things the calculation
depends on. Everything else is derived here, in the standard library:

* the SCF grid from the k-spacing, by the server's documented rule
  (``ceil(1 / (|a_i| * kspacing))`` snapped to the nearest odd count, the
  larger on a tie), on the built-in silicon cell — reconciled with the
  server's own ``qe_suggest_kpoints`` answers the table records;
* ``n_bands`` (8 per atom) and ``n_kpoints`` (the number of path points).

Generation refuses an instance whose measured record contradicts any of this,
so the reference is never quietly inconsistent with the server.

Two upstream properties that shape the reference
------------------------------------------------
* Which pseudopotential file an element gets follows the host's directory
  order (D1 in the smoke). The table records the Si file it was measured with
  and the reference carries it: the agent reports the file the server indexes,
  so a host that picks differently shows up as a wrong ``si_pseudopotential``
  instead of as unexplained energy differences. Measured on aarch64 and amd64:
  both pick ``Si_ONCV_PBE-1.2.upf``.
* The density cutoff is never on the MCP surface: the server keeps ``ecutrho``
  at the hint table's 120 Ry whatever ``ecutwfc`` is. The cutoffs stay at or
  below 30 Ry so the density cutoff is at least four times the wavefunction
  cutoff, as norm-conserving pseudopotentials need.

Framework call: python generate_gt.py --output-dir <dir> --params '<json>'
Standard library only.
"""
from __future__ import annotations

import argparse
import json
import math
import random
import time
from pathlib import Path

INPUT_SPEC = [
    {"name": "calculation.json", "description": "the structure, plane-wave cutoff, k-point "
                                                "spacing and number of band-path points the "
                                                "chain must use"},
]
OUTPUT_SPEC = [
    {"name": "result.json", "description": "pseudopotential, SCF grid, energies, band edges and "
                                           "band-file facts as the tools returned them"},
]
DEFAULT_PARAMS = {"seed": 0}

# ---------------------------------------------------------------------------
# The instance grid (keep in step with scripts/mcp/e2e/measure_qe_table.py)
# ---------------------------------------------------------------------------
STRUCTURE = "Si"             # the server's built-in: bulk('Si', 'diamond', a=5.43), primitive fcc
ECUTWFC = (20, 25, 30)       # Ry; ecutrho stays at 120 Ry (see the module docstring)
KSPACING = (0.06, 0.04, 0.03)   # 1/Å -> 5x5x5, 7x7x7, 9x9x9
NPOINTS_BAND = (20, 30, 40)

SI_A = 5.43                  # Å, conventional cubic
N_ATOMS = 2
ECUTRHO_RY = 120             # the hint table's Si density cutoff, which the server always uses
PREFERRED_KPTS = (1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21)
# 1 / (|a| * kspacing) must sit at least this far from an integer, so the
# ceiling in the grid rule is not decided by rounding.
CEIL_MARGIN = 0.05

MCP_TOOLS = ("qe_list_pseudopotentials", "qe_suggest_kpoints", "qe_workflow_bandstructure",
             "qe_list_files", "qe_read_bands")
# The plain files a band-structure run leaves (qe_list_files skips the pseudo/
# and tmp/ directories); measured, and identical at every grid point.
RUN_FILES = ("bands.dat", "bands.dat.gnu", "bands.dat.rap", "bands.in", "bands.out",
             "nscf.in", "nscf.out", "scf.in", "scf.out")


# >>> BEGIN MEASURED TABLE >>>
# Generated by scripts/mcp/e2e/measure_qe_table.py against qe-mcp eecdbbe8931a840f6010d8bae73dea1bf5501717
# and the committed conda lock, on aarch64 (Linux-6.8.0-138-generic-aarch64-with-glibc2.35),
# 27 chains in 180 s, 2026-10-07.
# Replace wholesale when either is bumped; never hand-edit a value.
MEASURED = {
    'si_pseudopotential': 'Si_ONCV_PBE-1.2.upf',
    'si_cutoff_hints_ry': [30, 120],
    'suggested_grid_by_kspacing': {'0.03': [9, 9, 9], '0.04': [7, 7, 7], '0.06': [5, 5, 5]},
    'points': {
        (20, 5, 20): {
            'total_energy_eV': -214.38133096286373,
            'fermi_energy_eV': 6.4991,
            'band_gap_eV': 0.694,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.271,
            'cbm_eV': 6.965,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 5, 30): {
            'total_energy_eV': -214.38133096286373,
            'fermi_energy_eV': 6.4991,
            'band_gap_eV': 0.5949999999999998,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.271,
            'cbm_eV': 6.866,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 5, 40): {
            'total_energy_eV': -214.38133096286373,
            'fermi_energy_eV': 6.4991,
            'band_gap_eV': 0.5609999999999999,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.271,
            'cbm_eV': 6.832,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 7, 20): {
            'total_energy_eV': -214.4121060883094,
            'fermi_energy_eV': 6.5035,
            'band_gap_eV': 0.6980000000000004,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.257,
            'cbm_eV': 6.955,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 7, 30): {
            'total_energy_eV': -214.4121060883094,
            'fermi_energy_eV': 6.5035,
            'band_gap_eV': 0.5990000000000002,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.257,
            'cbm_eV': 6.856,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 7, 40): {
            'total_energy_eV': -214.4121060883094,
            'fermi_energy_eV': 6.5035,
            'band_gap_eV': 0.5640000000000001,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.257,
            'cbm_eV': 6.821,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 9, 20): {
            'total_energy_eV': -214.4181338185337,
            'fermi_energy_eV': 6.6238,
            'band_gap_eV': 0.6990000000000007,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.254,
            'cbm_eV': 6.953,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 9, 30): {
            'total_energy_eV': -214.4181338185337,
            'fermi_energy_eV': 6.6238,
            'band_gap_eV': 0.5990000000000002,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.254,
            'cbm_eV': 6.853,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (20, 9, 40): {
            'total_energy_eV': -214.4181338185337,
            'fermi_energy_eV': 6.6238,
            'band_gap_eV': 0.5650000000000004,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.254,
            'cbm_eV': 6.819,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 5, 20): {
            'total_energy_eV': -214.41413374475556,
            'fermi_energy_eV': 6.4864,
            'band_gap_eV': 0.6909999999999998,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.258,
            'cbm_eV': 6.949,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 5, 30): {
            'total_energy_eV': -214.41413374475556,
            'fermi_energy_eV': 6.4864,
            'band_gap_eV': 0.5979999999999999,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.258,
            'cbm_eV': 6.856,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 5, 40): {
            'total_energy_eV': -214.41413374475556,
            'fermi_energy_eV': 6.4864,
            'band_gap_eV': 0.5629999999999997,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.258,
            'cbm_eV': 6.821,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 7, 20): {
            'total_energy_eV': -214.4454061582849,
            'fermi_energy_eV': 6.4964,
            'band_gap_eV': 0.694,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.244,
            'cbm_eV': 6.938,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 7, 30): {
            'total_energy_eV': -214.4454061582849,
            'fermi_energy_eV': 6.4964,
            'band_gap_eV': 0.601,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.244,
            'cbm_eV': 6.845,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 7, 40): {
            'total_energy_eV': -214.4454061582849,
            'fermi_energy_eV': 6.4964,
            'band_gap_eV': 0.5659999999999998,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.244,
            'cbm_eV': 6.81,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 9, 20): {
            'total_energy_eV': -214.45199947717228,
            'fermi_energy_eV': 6.6117,
            'band_gap_eV': 0.6950000000000003,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.241,
            'cbm_eV': 6.936,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 9, 30): {
            'total_energy_eV': -214.45199947717228,
            'fermi_energy_eV': 6.6117,
            'band_gap_eV': 0.6020000000000003,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.241,
            'cbm_eV': 6.843,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (25, 9, 40): {
            'total_energy_eV': -214.45199947717228,
            'fermi_energy_eV': 6.6117,
            'band_gap_eV': 0.5670000000000002,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.241,
            'cbm_eV': 6.808,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 5, 20): {
            'total_energy_eV': -214.42591409808915,
            'fermi_energy_eV': 6.4789,
            'band_gap_eV': 0.6890000000000001,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.251,
            'cbm_eV': 6.94,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 5, 30): {
            'total_energy_eV': -214.42591409808915,
            'fermi_energy_eV': 6.4789,
            'band_gap_eV': 0.5949999999999998,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.251,
            'cbm_eV': 6.846,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 5, 40): {
            'total_energy_eV': -214.42591409808915,
            'fermi_energy_eV': 6.4789,
            'band_gap_eV': 0.5599999999999996,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.251,
            'cbm_eV': 6.811,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 7, 20): {
            'total_energy_eV': -214.45630404636253,
            'fermi_energy_eV': 6.4911,
            'band_gap_eV': 0.6929999999999996,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.237,
            'cbm_eV': 6.93,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 7, 30): {
            'total_energy_eV': -214.45630404636253,
            'fermi_energy_eV': 6.4911,
            'band_gap_eV': 0.5990000000000002,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.237,
            'cbm_eV': 6.836,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 7, 40): {
            'total_energy_eV': -214.45630404636253,
            'fermi_energy_eV': 6.4911,
            'band_gap_eV': 0.5640000000000001,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.237,
            'cbm_eV': 6.801,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 9, 20): {
            'total_energy_eV': -214.4631354648796,
            'fermi_energy_eV': 6.6039,
            'band_gap_eV': 0.694,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.234,
            'cbm_eV': 6.928,
            'n_bands': 16,
            'n_kpoints': 20,
            'path_length': 4.9721,
            'read_n_kpoints': 20,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 9, 30): {
            'total_energy_eV': -214.4631354648796,
            'fermi_energy_eV': 6.6039,
            'band_gap_eV': 0.5999999999999996,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.234,
            'cbm_eV': 6.834,
            'n_bands': 16,
            'n_kpoints': 30,
            'path_length': 4.9721,
            'read_n_kpoints': 30,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
        (30, 9, 40): {
            'total_energy_eV': -214.4631354648796,
            'fermi_energy_eV': 6.6039,
            'band_gap_eV': 0.5650000000000004,
            'is_direct_gap': False,
            'is_metal': False,
            'vbm_eV': 6.234,
            'cbm_eV': 6.799,
            'n_bands': 16,
            'n_kpoints': 40,
            'path_length': 4.9721,
            'read_n_kpoints': 40,
            'file_names': ['bands.dat', 'bands.dat.gnu', 'bands.dat.rap', 'bands.in', 'bands.out', 'nscf.in', 'nscf.out', 'scf.in', 'scf.out'],
            'pseudo_copied': ['Si_ONCV_PBE-1.2.upf'],
        },
    },
}
# <<< END MEASURED TABLE <<<


class GenerationError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# The k-grid policy (structures.suggest_kpoints with an explicit kspacing)
# ---------------------------------------------------------------------------

def si_cell_length() -> float:
    """|a_i| of the primitive fcc cell of diamond silicon: a / sqrt(2)."""
    return SI_A / math.sqrt(2.0)


def snap_odd(n: int) -> int:
    """Nearest value of PREFERRED_KPTS, the larger one on a tie."""
    if n <= 1:
        return 1
    if n >= PREFERRED_KPTS[-1]:
        return PREFERRED_KPTS[-1]
    return min(PREFERRED_KPTS, key=lambda p: (abs(n - p), -p))


def kgrid(kspacing: float) -> list[int]:
    raw = 1.0 / (si_cell_length() * kspacing)
    if abs(raw - round(raw)) < CEIL_MARGIN:
        raise GenerationError(f"1/(|a| kspacing) = {raw:.4f} is too close to an integer for "
                              f"kspacing={kspacing}; the grid would hang on rounding")
    return [snap_odd(max(1, math.ceil(raw)))] * 3


# ---------------------------------------------------------------------------
# The instance
# ---------------------------------------------------------------------------

def build_case(seed: int) -> dict:
    rng = random.Random(seed)
    return {
        "structure": STRUCTURE,
        "ecutwfc": ECUTWFC[rng.randrange(len(ECUTWFC))],
        "kspacing": KSPACING[rng.randrange(len(KSPACING))],
        "npoints_band": NPOINTS_BAND[rng.randrange(len(NPOINTS_BAND))],
        "result_file": "result.json",
    }


def reference(case: dict) -> dict:
    if case["ecutwfc"] * 4 > ECUTRHO_RY:
        raise GenerationError(f"ecutwfc={case['ecutwfc']} Ry with the fixed ecutrho={ECUTRHO_RY} Ry "
                              "is below the norm-conserving dual of 4")
    grid = kgrid(case["kspacing"])
    suggested = MEASURED["suggested_grid_by_kspacing"].get(repr(case["kspacing"]))
    if suggested != grid:
        raise GenerationError(f"the grid rule gives {grid} for kspacing={case['kspacing']} but the "
                              f"server suggested {suggested}")
    point = (case["ecutwfc"], grid[0], case["npoints_band"])
    measured = MEASURED["points"].get(point)
    if measured is None:
        raise GenerationError(f"no measured run for (ecutwfc, grid, npoints_band) = {point}; "
                              "regenerate MEASURED with scripts/mcp/e2e/measure_qe_table.py "
                              f"(have {sorted(MEASURED['points'])})")

    pseudo = MEASURED["si_pseudopotential"]
    problems = []
    if measured["pseudo_copied"] != [pseudo]:
        problems.append(f"the run copied {measured['pseudo_copied']}, the index says {pseudo}")
    if measured["n_bands"] != 8 * N_ATOMS:
        problems.append(f"n_bands {measured['n_bands']} != 8 x {N_ATOMS}")
    if not measured["n_kpoints"] == measured["read_n_kpoints"] == case["npoints_band"]:
        problems.append(f"n_kpoints {measured['n_kpoints']} / read {measured['read_n_kpoints']} "
                        f"!= npoints_band {case['npoints_band']}")
    if measured["file_names"] != list(RUN_FILES):
        problems.append(f"the run left {measured['file_names']}, expected {list(RUN_FILES)}")
    if measured["is_metal"] or measured["band_gap_eV"] is None or measured["band_gap_eV"] <= 0:
        problems.append("no band gap")
    elif abs(measured["cbm_eV"] - measured["vbm_eV"] - measured["band_gap_eV"]) > 1e-9:
        problems.append("band_gap_eV is not cbm_eV - vbm_eV")
    if problems:
        raise GenerationError(f"measured record {point} is inconsistent: " + "; ".join(problems))

    return {
        "si_pseudopotential": pseudo,
        "scf_kpoints": grid,
        "total_energy_eV": measured["total_energy_eV"],
        "fermi_energy_eV": measured["fermi_energy_eV"],
        "band_gap_eV": measured["band_gap_eV"],
        "vbm_eV": measured["vbm_eV"],
        "cbm_eV": measured["cbm_eV"],
        "is_direct_gap": measured["is_direct_gap"],
        "n_bands": measured["n_bands"],
        "n_kpoints": measured["n_kpoints"],
        "path_length": measured["path_length"],
        # What the verifier compares qe_list_files against (a subset of the listing).
        "file_names": list(RUN_FILES),
        "ecutrho_ry": ECUTRHO_RY,
        "n_atoms": N_ATOMS,
        "mcp_tools": list(MCP_TOOLS),
    }


# ---------------------------------------------------------------------------
# Framework entry point
# ---------------------------------------------------------------------------

def render_prompts(task_dir: Path, output_dir: Path, case: dict) -> None:
    for level in ("b1", "b2", "b3", "b4"):
        text = (task_dir / f"prompt_{level}.md").read_text(encoding="utf-8")
        for key, value in case.items():
            text = text.replace("{{" + key + "}}", str(value))
        if "{{" in text:
            raise GenerationError(f"unresolved placeholder in prompt_{level}.md")
        (output_dir / f"prompt_{level}.md").write_text(text, encoding="utf-8")


def generate(output_dir: Path, params: dict) -> dict:
    merged = {**DEFAULT_PARAMS, **params}
    started = time.time()
    output_dir = Path(output_dir)
    data_dir, ref_dir = output_dir / "data", output_dir / "reference"
    data_dir.mkdir(parents=True, exist_ok=True)
    ref_dir.mkdir(parents=True, exist_ok=True)

    case = build_case(int(merged["seed"]))
    ref = reference(case)
    numbers = [value for value in ref.values() if isinstance(value, float)]
    if not all(math.isfinite(value) for value in numbers):
        raise GenerationError("non-finite reference")

    (data_dir / "calculation.json").write_text(json.dumps(case, indent=2) + "\n", encoding="utf-8")
    (ref_dir / "reference.json").write_text(json.dumps({**case, **ref}, indent=2) + "\n",
                                            encoding="utf-8")
    render_prompts(Path(__file__).resolve().parent, output_dir, case)
    meta = {
        "params_used": merged,
        "input_files": [spec["name"] for spec in INPUT_SPEC],
        "reference_files": ["reference.json"],
        "generation_time_seconds": round(time.time() - started, 2),
    }
    (output_dir / "instance_meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return meta


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--params", type=str, default="{}")
    args = parser.parse_args()
    print(json.dumps(generate(args.output_dir, json.loads(args.params)), indent=2))
